from tomato import logger
#from tomato.pipeline.stage_01_data_ingestion import DataIngestionTrainingPipeline
#from tomato.pipeline.stage_02_prepare_base_model import PrepareBaseModelTrainingPipeline
#from tomato.pipeline.stage_03_model_trainer import ModelTrainingPipeline
#from tomato.pipeline.stage_04_model_evaluation import EvaluationPipeline
